version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - python your_lambda_script.py
  post_build:
    commands:
      - echo Build completed on `date`
